package com.gztoucher.Image2ByteVar;

import java.io.*;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Locale;

class CodeTool {

    String convertFromDir(String dir) {
        String ext = ".png";
        File[] files = FileUtils.listFiles(dir, ext);
        if (files == null || files.length == 0) {
            System.out.println("files is empty");
            return "";
        }
        StringBuilder builder = new StringBuilder();
        builder.append("/**\n");
        builder.append(" * Generated by https://github.com/gzu-liyujiang/Image2ByteVar\n");
        builder.append(" *\n");
        builder.append(" * @author 李玉江[QQ:1023694760]\n");
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm", Locale.PRC);
        builder.append(" * @since ");
        builder.append(sdf.format(new Date(System.currentTimeMillis())));
        builder.append("\n");
        builder.append(" */\n");
        builder.append("public class XyzIcon {\n\n");
        for (File file : files) {
            builder.append(convert(file.getName().replace(ext, ""), file.getAbsolutePath()));
        }
        builder.append("\n}\n");
        return builder.toString();
    }

    String convert(String varName, String path) {
        byte[] data = FileUtils.readBytes(path);
        if (null == data) {
            System.out.println("data is null");
            return "";
        }
        StringBuilder builder = new StringBuilder();
        builder.append("\tpublic static final byte[] ");
        builder.append(varName.toUpperCase());
        builder.append(" = {");
        int length = data.length;
        int count = 0;
        for (int i = 0; i < length; i++) {
            count++;
            if (i == length - 1) {
                builder.append(data[i]);
            } else {
                builder.append(data[i]).append(",");
            }
            if (count % 20 == 0) {
                builder.append("\n\t\t");
            }
        }
        builder.append(" };\n");
        return builder.toString();
    }

}
